app = "tarun-adari-portfolio"
primary_region = "dfw"

[build]

[env]
  NODE_ENV = "production"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[[services.http_checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  path = "/"
